on: workflow_dispatch

#https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run
# try learning this instead
# workflow_run:

name: Publishes to Heroku
jobs:
  heroku:
    name: Deploy to heroku
    runs-on: ubuntu-latest
    # needs: [build]
    steps:
      - uses: actions/checkout@master

      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "${{ secrets.HEROKU_APP_NAME }}" #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
