name: Publishes to Dockerhub registry
jobs:
  publish:
    name: Publish to registry
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master

      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: xwth/test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
