# on: [push, pull_request]
on: push
name: Test and Publish builds on push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test project
        uses: actions/setup-go@v2
      - run: go test -v

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master

      - name: Golang run
        uses: cedrickring/golang-action@1.6.0

  publish:
    name: Publish to registry
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master

      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: xwth/test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
