on:
  push:
    branches:
      - master
name: My test Action
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Golang run
        uses: cedrickring/golang-action@1.5.2

      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: test/repo
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
