# on: [push, pull_request]
on: push
name: Test and Publish builds on push

jobs:
  # staticcheck:
  #   name: Static check and Caching modules
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Static Check
  #       run: |
  #         # add executables installed with go get to PATH
  #         # TODO: this will hopefully be fixed by
  #         # https://github.com/actions/setup-go/issues/14
  #         export PATH=${PATH}:`go env GOPATH`/bin
  #         go get -u honnef.co/go/tools/cmd/staticcheck
  #         staticcheck ./...
  #     - name: Cache Go modules
  #       uses: actions/cache@preview
  #       with:
  #         path: ~/go/pkg/mod
  #         key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
  #         restore-keys: |
  #           ${{ runner.OS }}-build-${{ env.cache-name }}-
  #           ${{ runner.OS }}-build-
  #           ${{ runner.OS }}-

  # test:
  #   name: Test
  #   # needs: staticcheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master

  #     - name: Test project
  #       uses: actions/setup-go@v2
  #     - run: go test -v

  build:
    name: Build
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - uses: actions/checkout@master

      - name: Golang run
        uses: cedrickring/golang-action@1.6.0

  publish:
    name: Publish to registry
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master

      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: xwth/test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  heroku:
    name: Deploy to heroku
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master

      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "${{ secrets.HEROKU_APP_NAME }}" #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
